#!/usr/bin/env python3
"""build_map.py - generate the Hekswerk system map (the circuit-quipu) from the manifest below.

The map is data-driven so it expands as reach builds: add a node (and an edge) to NODES/EDGES
and rerun. It emits a hand-drawn SVG circuit schematic ("quipu meets electrical-circuit diagram")
AND an always-visible plain-HTML fallback list, so every link works with or without JavaScript
(link-or-drop holds either way). The SVG uses CSS classes for colour, so the site's design tokens
flow straight through.

    python3 tools/build_map.py            # inject the map into index.html (between MAP markers)
    python3 tools/build_map.py --check    # verify every local link resolves; list external ones

Reading of the picture: the PRACTICE (relocation, automation, freelance eval - the part with
customers) is the power source. It funds the SUBSTRATE (where the research runs), whose output can
only reach the PUBLIC research surface by passing through the one gated junction, the MEMBRANE
(curation + leak-sweep + provenance). The practice has customers; the research is the funded,
published circuit it powers.

Iron rule (Littlebird R1): a node ships only if its link points at something that actually exists.
`--check` enforces the local half of that automatically.
"""
import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.normpath(os.path.join(HERE, ".."))
INDEX = os.path.join(SITE, "index.html")
MARK_START = "<!-- MAP:START (generated by tools/build_map.py - do not edit between markers) -->"
MARK_END = "<!-- MAP:END -->"

# ============================== THE MANIFEST (edit to expand) ==============================
# Zones, left to right. `id` maps to a CSS class on each chip + the fallback section.
ZONES = [
    {"id": "practice", "title": "Practice", "kind": "power",
     "blurb": "What funds it - the part with customers. The power source."},
    {"id": "substrate", "title": "Software", "kind": "work",
     "blurb": "Where the research runs and is recorded."},
    {"id": "membrane", "title": "Publishing", "kind": "gate",
     "blurb": "The one honest gate from private work to public: curation, leak-sweep, provenance."},
    {"id": "public", "title": "Research", "kind": "public",
     "blurb": "What anyone can read."},
]

# Each node: id, zone, label, plain (one plain-English line), href.
# Local hrefs start with "./"; --check resolves them (query/anchor stripped first).
NODES = [
    # --- the practice (power source) ---
    {"id": "relocation", "zone": "practice", "label": "relocation",
     "plain": "structured planning for US-to-Europe moves",
     "href": "./relocation.html"},
    {"id": "automation", "zone": "practice", "label": "automation",
     "plain": "fixed-scope, privacy-first automation builds",
     "href": "./contact.html?topic=automation"},
    {"id": "evalwork", "zone": "practice", "label": "freelance eval",
     "plain": "AI-evaluation contract work - the engine behind the research",
     "href": "./research.html#funding"},
    {"id": "contact", "zone": "practice", "label": "contact",
     "plain": "a short, private contact form",
     "href": "./contact.html"},

    # --- substrate ---
    {"id": "ww", "zone": "substrate", "label": "worldweaver",
     "plain": "the persistent shared world and its residents",
     "href": "https://github.com/libardo667/worldweaver"},
    {"id": "stable", "zone": "substrate", "label": "the-stable",
     "plain": "the familiar runtime, where the local minds live",
     "href": "https://github.com/libardo667/the-stable"},
    {"id": "prune", "zone": "substrate", "label": "prune",
     "plain": "write it down, build it, prune the living set",
     "href": "https://github.com/libardo667/prune"},
    {"id": "memmgmt", "zone": "substrate", "label": "memory-management",
     "plain": "reusable external memory for any project",
     "href": "https://github.com/libardo667/memory-management"},
    {"id": "revsched", "zone": "substrate", "label": "review-scheduler",
     "plain": "a cold reviewer that can't be charmed",
     "href": "https://github.com/libardo667/review-scheduler"},
    {"id": "record", "zone": "substrate", "label": "the research record",
     "plain": "locked pre-registrations and the cold-review history",
     "href": "https://github.com/libardo667/worldweaver/tree/main/research"},

    # --- membrane ---
    {"id": "curation", "zone": "membrane", "label": "curation + leak-sweep",
     "plain": "raw work trimmed to legible artifacts; private data excluded",
     "href": "https://github.com/libardo667/memory-management"},
    {"id": "provenance", "zone": "membrane", "label": "provenance",
     "plain": "every public page records how it was made and whose words are whose",
     "href": "./exhibits/honesty-machinery.html"},

    # --- public research surface ---
    {"id": "research", "zone": "public", "label": "the research wing",
     "plain": "the research, methods-first, in the open",
     "href": "./research.html"},
    {"id": "library", "zone": "public", "label": "the library",
     "plain": "methodology + research wings, the sourced record",
     "href": "https://github.com/libardo667/hekswerk"},
    {"id": "exhibits", "zone": "public", "label": "the exhibits",
     "plain": "walkable proofs you can inspect",
     "href": "./exhibits/index.html"},

    # --- exhibits (children of `exhibits`; rendered as a sub-cord) ---
    {"id": "ex_two", "zone": "public", "label": "Two Weeks", "parent": "exhibits",
     "plain": "the work, counted across six dimensions", "href": "./exhibits/two-weeks.html"},
    {"id": "ex_mono", "zone": "public", "label": "Fifteen Strangers", "parent": "exhibits",
     "plain": "a topic-monoculture null, kept and shown", "href": "./exhibits/topic-monoculture.html"},
    {"id": "ex_honesty", "zone": "public", "label": "The Honesty Machinery", "parent": "exhibits",
     "plain": "the verdicts that went against me, kept", "href": "./exhibits/honesty-machinery.html"},
    {"id": "ex_commons", "zone": "public", "label": "Why a Commons", "parent": "exhibits",
     "plain": "why federation is the only honest topology", "href": "./exhibits/why-a-commons.html"},
    {"id": "ex_kitchen", "zone": "public", "label": "The Kitchen", "parent": "exhibits",
     "plain": "2.6M words from stateless hands", "href": "./exhibits/the-kitchen.html"},
    {"id": "ex_apoth", "zone": "public", "label": "The Apothecary", "parent": "exhibits",
     "plain": "nine things you could build, graded by effort", "href": "./exhibits/the-apothecary.html"},
    {"id": "ex_pen", "zone": "public", "label": "The Pen's Workshop", "parent": "exhibits",
     "plain": "the collaborator's own kept prose", "href": "./exhibits/workshop/index.html"},
]

# Edges tell the flow. Cross-zone edges are drawn as circuit traces; same-zone structure is carried
# by the shared vertical cord. The power feed (practice -> substrate) is drawn separately.
EDGES = [
    ("prune", "ww"), ("prune", "stable"),
    ("memmgmt", "record"), ("revsched", "record"),
    ("ww", "curation"), ("stable", "curation"), ("record", "curation"),
    ("curation", "provenance"),
    ("provenance", "research"), ("provenance", "library"),
    ("research", "exhibits"), ("research", "library"),
]
# ===========================================================================================

ORIENT = ("Hekswerk in one picture. The practice - the part with customers - funds the software where "
          "the research runs; that work only becomes public after passing through one honest gate "
          "(curation, leak-sweep, provenance). The practice is sold; the research is funded and published.")

# --- layout geometry (SVG user units) ---
COLS_X = {"practice": 104, "substrate": 400, "membrane": 690, "public": 968}
CHIP_W, CHIP_H, HALF = 168, 40, 84
TOP, ROW = 104, 70          # first row y, vertical gap between top-level knots
KID_INDENT, KID_OFFSET, ROW_CH = 26, 52, 33   # exhibit sub-cord
VIEW_W = 1120

ZONE_OF = {n["id"]: n["zone"] for n in NODES}


def _by_zone(zone):
    return [n for n in NODES if n["zone"] == zone and not n.get("parent")]


def _children(parent_id):
    return [n for n in NODES if n.get("parent") == parent_id]


def layout():
    """Return {id: (cx, cy)} and the max y used (for viewBox height)."""
    pos, max_y = {}, 0
    for z in ZONES:
        cx = COLS_X[z["id"]]
        y = TOP
        for n in _by_zone(z["id"]):
            pos[n["id"]] = (cx, y)
            kids = _children(n["id"])
            if kids:
                ky = y + KID_OFFSET
                for k in kids:
                    pos[k["id"]] = (cx + KID_INDENT, ky)
                    ky += ROW_CH
                y = ky + (ROW - ROW_CH)
            else:
                y += ROW
            max_y = max(max_y, y)
    return pos, max_y


def _chip(n, x, y, kid=False):
    w = CHIP_W if not kid else CHIP_W - 16
    h = CHIP_H if not kid else CHIP_H - 8
    half = w / 2
    cls = "chip kid" if kid else "chip"
    label = html.escape(n["label"])
    title = html.escape(n["plain"])
    fs = 12 if not kid else 11
    return (
        f'<a class="{cls} z-{n["zone"]}" href="{html.escape(n["href"])}" data-node="{n["id"]}">'
        f'<title>{label} - {title}</title>'
        f'<rect x="{x-half:.0f}" y="{y-h/2:.0f}" width="{w:.0f}" height="{h:.0f}" rx="9"/>'
        f'<circle class="knot" cx="{x-half:.0f}" cy="{y:.0f}" r="4"/>'
        f'<text x="{x:.0f}" y="{y+fs*0.35:.0f}" font-size="{fs}">{label}</text>'
        f'</a>'
    )


def _trace(a, b, pos):
    """Orthogonal L-route from the right edge of a to the left edge of b (a is left of b)."""
    ax, ay = pos[a]
    bx, by = pos[b]
    x1, x2 = ax + HALF, bx - HALF
    midx = (x1 + x2) / 2
    d = f"M{x1:.0f},{ay:.0f} H{midx:.0f} V{by:.0f} H{x2:.0f}"
    dots = (f'<circle class="junction" cx="{midx:.0f}" cy="{by:.0f}" r="3"/>'
            f'<circle class="junction" cx="{x2:.0f}" cy="{by:.0f}" r="3.5"/>')
    return f'<path class="trace t-from-{a} t-to-{b}" d="{d}"/>{dots}'


def circuit_svg() -> str:
    pos, max_y = layout()
    height = int(max_y + 36)
    out = [f'<svg class="circuit" viewBox="0 0 {VIEW_W} {height}" role="img" '
           f'aria-label="System map: the practice funds the software, which becomes public through one honest publishing gate.">']

    # primary cord (the quipu top rail, spanning all four cords) + power feed (practice -> substrate)
    rail_y = TOP - 46
    pcord = COLS_X["practice"] - HALF
    scord = COLS_X["substrate"] - HALF
    pubcord = COLS_X["public"] - HALF
    out.append(f'<line class="rail" x1="{pcord}" y1="{rail_y}" x2="{pubcord}" y2="{rail_y}"/>')
    out.append(f'<path class="trace power t-from-practice t-to-substrate" '
               f'd="M{pcord},{rail_y} H{scord} V{TOP-18}"/>')
    out.append(f'<g class="source"><circle cx="{pcord}" cy="{rail_y}" r="6"/></g>')

    # zone cords (vertical) + headers
    for z in ZONES:
        cx = COLS_X[z["id"]]
        tops = _by_zone(z["id"])
        if not tops:
            continue
        ys = [pos[n["id"]][1] for n in tops]
        kids_ys = [pos[k["id"]][1] for n in tops for k in _children(n["id"])]
        y0, y1 = min(ys), max(ys + kids_ys)
        out.append(f'<line class="cord z-{z["id"]}" x1="{cx-HALF}" y1="{rail_y}" x2="{cx-HALF}" y2="{y1}"/>')
        out.append(f'<text class="zone-label z-{z["id"]}" x="{cx}" y="{TOP-58}" text-anchor="middle">'
                   f'{html.escape(z["title"])}</text>')

    # traces (cross-zone edges only; same-zone structure is the cord)
    for a, b in EDGES:
        if ZONE_OF.get(a) != ZONE_OF.get(b):
            out.append(_trace(a, b, pos))

    # chips
    for z in ZONES:
        for n in _by_zone(z["id"]):
            x, y = pos[n["id"]]
            out.append(_chip(n, x, y))
            for k in _children(n["id"]):
                kx, ky = pos[k["id"]]
                out.append(_chip(k, kx, ky, kid=True))

    out.append("</svg>")
    return "\n".join(out)


def fallback() -> str:
    out = ['<div class="map-list">']
    for z in ZONES:
        out.append(f'<section class="zone z-{z["id"]}"><h2>{html.escape(z["title"])}</h2>'
                   f'<p class="zb">{html.escape(z["blurb"])}</p><ul>')
        for n in _by_zone(z["id"]):
            out.append(f'<li><a href="{html.escape(n["href"])}"><b>{html.escape(n["label"])}</b></a> '
                       f'<span>{html.escape(n["plain"])}</span>')
            kids = _children(n["id"])
            if kids:
                out.append("<ul>")
                for k in kids:
                    out.append(f'<li><a href="{html.escape(k["href"])}"><b>{html.escape(k["label"])}</b></a> '
                               f'<span>{html.escape(k["plain"])}</span></li>')
                out.append("</ul>")
            out.append("</li>")
        out.append("</ul></section>")
    out.append("</div>")
    return "\n".join(out)


HOVER_JS = """<script>
(function(){
  var svg=document.currentScript.previousElementSibling;
  if(!svg||!svg.querySelector)return;
  svg.querySelectorAll('.chip').forEach(function(c){
    var id=c.getAttribute('data-node');
    function set(on){
      svg.querySelectorAll('.t-from-'+id+',.t-to-'+id).forEach(function(t){t.classList.toggle('lit',on);});
      c.classList.toggle('lit',on);
    }
    c.addEventListener('mouseenter',function(){set(true);});
    c.addEventListener('mouseleave',function(){set(false);});
    c.addEventListener('focus',function(){set(true);});
    c.addEventListener('blur',function(){set(false);});
  });
})();
</script>"""


def map_section() -> str:
    """The injectable fragment: intro + SVG circuit + JS-free fallback list + hover enhancement."""
    return "\n".join([
        f'<p class="map-orient">{html.escape(ORIENT)}</p>',
        '<div class="circuit-wrap">',
        circuit_svg(),
        HOVER_JS,
        '</div>',
        '<p class="map-note">The same map as a list - every node links to something real:</p>',
        fallback(),
    ])


def inject():
    with open(INDEX, "r", encoding="utf-8") as f:
        doc = f.read()
    if MARK_START not in doc or MARK_END not in doc:
        print(f"ERROR: markers not found in {INDEX}. Add:\n  {MARK_START}\n  {MARK_END}")
        return 1
    block = f"{MARK_START}\n{map_section()}\n{MARK_END}"
    new = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), lambda _: block, doc, flags=re.S)
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(new)
    print(f"injected map into {INDEX}  ({len(NODES)} nodes, {len(EDGES)} edges)")
    return 0


def check() -> int:
    bad, ext = [], []
    ids = {n["id"] for n in NODES}
    for n in NODES:
        h = n["href"]
        if h.startswith("./"):
            local = h.split("#")[0].split("?")[0]
            p = os.path.normpath(os.path.join(SITE, local[2:]))
            if not os.path.exists(p):
                bad.append(f'{n["id"]}: local link missing -> {h}')
        else:
            ext.append(f'{n["id"]}: {h}')
    for a, b in EDGES:
        for e in (a, b):
            if e not in ids:
                bad.append(f"edge references unknown node: {e}")
    print("LINK-OR-DROP CHECK")
    print(f"  nodes: {len(NODES)}  edges: {len(EDGES)}")
    if bad:
        print("  BROKEN (fix or drop before shipping):")
        for b in bad:
            print("   -", b)
    else:
        print("  all local links resolve, all edges reference real nodes.")
    print("  external links to eyeball:")
    for e in ext:
        print("   -", e)
    return 1 if bad else 0


def main():
    if "--check" in sys.argv:
        sys.exit(check())
    sys.exit(inject())


if __name__ == "__main__":
    main()
